language: scala

jdk:
  - openjdk11

scala:
  - 2.13.1

before_install:
  - git fetch --tags

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete

cache:
  directories:
    - $HOME/.cache
    - $HOME/.coursier
    - $HOME/.ivy2
    - $HOME/.m2
    - $HOME/.sbt

script: sbt validate

after_success:
  - bash <(curl -s https://codecov.io/bash)
